version: '3.8'
services:

    db:
        image: mysql
        container_name: test_db_dockerSymfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: test_phpmyadmin_dockerSymfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: test_maildev_dockerSymfony
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - 8081:80
        restart: always
        networks:
            - dev

    www:
        build: php
        container_name: test_www_dockerSymfony
        ports:
            - 8741:80
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev



networks:
    dev:

volumes:
    db-data: